gitlab_repo       = "torque4/infra_platform"
github_owner      = "Charungooa"
github_repo_name  = "github_myapp_infra_platform"
# github_token      = "ghp_yourGitHubPersonalAccessToken"
# gitlab_token      = "glpat_yourGitLabToken"
key_vault_name    = "myAppKeyVault012"
azure_resource_group = "gitlab-migration-rg-infra_platform"

# azure_tenant_id   = "your-tenant-id-guid"
# azure_object_id   = "your-user-or-sp-object-guid"
